server:
  port: 7777
spring:
  kafka:
    binder:
      replication-factor: 1
    topic:
      request-demo: request-demo
      reply-demo: reply-demo
      request-demo-2: request-demo-2
      reply-demo-2: reply-demo-2
    consumer:
      bootstrap-servers: localhost:9092
      group-id: demoProducerGroup
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9092